/** Machine-consumable deletion/gate inventory for the private F1-I convergence node. */
export const F1_I_DOCUMENT_SESSION_INVENTORY = {
  facadeSymbol: "getDocumentSessionRegistry",
  productionCallers: [
    "apps/app/src/client/query/useDraftReviewMutations.ts",
    "apps/app/src/core/editor/change-trail-navigation.ts",
    "apps/app/src/core/editor/passage-navigation.ts",
    "apps/app/src/features/chat/DraftReviewProvider.tsx",
    "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
    "apps/app/src/features/editor/EditorView.tsx",
    "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
    "apps/app/src/features/project/ContextPaneController.tsx",
    "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
    "apps/app/src/features/project/context/IdentityPlacementField.tsx",
    "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
    "apps/app/src/features/project/context/useCatalogWorkingSetReconciler.ts",
    "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
  ],
  prototypeCommentCallers: ["apps/app/src/features/proto/spike-layout/SpikeEditorSurface.tsx"],
  symbolsToDelete: [
    "TemporaryUnfencedDocumentSessionRegistry",
    "getDocumentSessionRegistry",
    "temporaryGet",
    "temporaryGetDetached",
    "temporaryAttachDetached",
    "temporaryRestartUnavailableRoom",
    "temporaryRetain",
    "temporaryRelease",
    "temporaryPeek",
    "temporaryRevokeRoom",
    "temporaryObserve",
    "temporaryGetLive",
    "roomSessionPersistenceKey",
    "useCatalogWorkingSetReconciler",
  ],
  negativeSpacePatterns: [
    "getDocumentSessionRegistry",
    "revokeRoom\\(",
    "destroyRoom\\(",
    "new DocumentSession\\(",
    "roomSessionPersistenceKey",
    "useCatalogWorkingSetReconciler",
  ],
  compileNegativeBareCalls: [
    "get(documentId)",
    "getDetached(documentId)",
    "attachDetached(documentId)",
    "restartUnavailableRoom(documentId)",
    "retain(ownerId, [documentId])",
  ],
} as const;
