/** Exact source-derived F1-I deletion inventory. */
export const F1_I_DOCUMENT_SESSION_INVENTORY = {
  expectedRecords: [
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 68,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 35,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 37,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 53,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 56,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 226,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 142,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 145,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 252,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 342,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 441,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 133,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 150,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 260,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 106,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 455,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 138,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 145,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 146,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 148,
    },
    {
      kind: "canonical-constructor",
      symbol: "DocumentSession",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 497,
    },
    {
      kind: "concrete-exposure",
      symbol: "DocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 61,
    },
    {
      kind: "concrete-exposure",
      symbol: "document-session-registry-implementation",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 9,
    },
    {
      kind: "facade-definition",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 65,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 8,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 5,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 23,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 27,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 5,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 35,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 25,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 16,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 36,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 18,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 9,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 20,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 68,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 21,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 33,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 44,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 51,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 188,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 225,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 37,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 139,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 251,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 73,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 341,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 441,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 133,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 140,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 150,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 260,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 106,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 455,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 23,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 138,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 145,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 146,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 148,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 153,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 51,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 81,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 344,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/test-support/UntitledLifecycleRig.ts",
      line: 272,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 40,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 40,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler.ts",
      line: 97,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler.ts",
      line: 528,
    },
    {
      kind: "legacy-owner",
      symbol: "revokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 50,
    },
    {
      kind: "legacy-owner",
      symbol: "revokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 80,
    },
    {
      kind: "raw-authority",
      symbol: "BroadcastChannel",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 160,
    },
    {
      kind: "raw-authority",
      symbol: "BroadcastChannel",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 161,
    },
    {
      kind: "raw-authority",
      symbol: "BroadcastChannel",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 163,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 24,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 145,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 191,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 802,
    },
    {
      kind: "raw-authority",
      symbol: "meridian:f1d:v1:",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 16,
    },
    {
      kind: "raw-authority",
      symbol: "navigator.locks",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 147,
    },
    {
      kind: "transitional",
      symbol: "TemporaryUnfencedDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 35,
    },
    {
      kind: "transitional",
      symbol: "TemporaryUnfencedDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 57,
    },
    {
      kind: "transitional",
      symbol: "TemporaryUnfencedDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 65,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 8,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 68,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 5,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 21,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 33,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 65,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 23,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 44,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 51,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 27,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 188,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 225,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 5,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 37,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 35,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 139,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 251,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 25,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 73,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 16,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 341,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/ContextPaneController.tsx",
      line: 441,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 36,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 133,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 140,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 150,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 260,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 18,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 106,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 455,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 9,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 23,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 20,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 138,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 145,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 146,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 148,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 153,
    },
    {
      kind: "transitional",
      symbol: "temporaryAttachDetached",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 658,
    },
    {
      kind: "transitional",
      symbol: "temporaryAttachDetached",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 73,
    },
    {
      kind: "transitional",
      symbol: "temporaryGet",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 647,
    },
    {
      kind: "transitional",
      symbol: "temporaryGet",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 70,
    },
    {
      kind: "transitional",
      symbol: "temporaryGet",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 71,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetDetached",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 654,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetDetached",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 659,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetDetached",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 72,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 612,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 651,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 655,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 734,
    },
    {
      kind: "transitional",
      symbol: "temporaryObserve",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 727,
    },
    {
      kind: "transitional",
      symbol: "temporaryObserve",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 79,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 665,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 704,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 77,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 78,
    },
    {
      kind: "transitional",
      symbol: "temporaryRelease",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 723,
    },
    {
      kind: "transitional",
      symbol: "temporaryRelease",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 76,
    },
    {
      kind: "transitional",
      symbol: "temporaryRestartUnavailableRoom",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 664,
    },
    {
      kind: "transitional",
      symbol: "temporaryRestartUnavailableRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 74,
    },
    {
      kind: "transitional",
      symbol: "temporaryRetain",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 681,
    },
    {
      kind: "transitional",
      symbol: "temporaryRetain",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 75,
    },
    {
      kind: "transitional",
      symbol: "temporaryRevokeRoom",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 712,
    },
    {
      kind: "transitional",
      symbol: "temporaryRevokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 80,
    },
    {
      kind: "transitional",
      symbol: "temporaryRevokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 81,
    },
    {
      kind: "unqualified-owner",
      symbol: "roomSessionPersistenceKey",
      file: "apps/app/src/core/editor/document-session.ts",
      line: 64,
    },
    {
      kind: "unqualified-owner",
      symbol: "roomSessionPersistenceKey",
      file: "apps/app/src/core/editor/document-session.ts",
      line: 232,
    },
    {
      kind: "unqualified-owner",
      symbol: "useCatalogWorkingSetReconciler",
      file: "apps/app/src/features/project/ProjectView.tsx",
      line: 43,
    },
    {
      kind: "unqualified-owner",
      symbol: "useCatalogWorkingSetReconciler",
      file: "apps/app/src/features/project/ProjectView.tsx",
      line: 127,
    },
    {
      kind: "unqualified-owner",
      symbol: "useCatalogWorkingSetReconciler",
      file: "apps/app/src/features/project/context/useCatalogWorkingSetReconciler.ts",
      line: 56,
    },
  ],
} as const;
