/** Exact source-derived F1-I deletion inventory. */
export const F1_I_DOCUMENT_SESSION_INVENTORY = {
  expectedRecords: [
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 68,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 35,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 37,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 53,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 56,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 226,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 151,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 154,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 261,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 184,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 208,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 120,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 469,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 138,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 145,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 146,
    },
    {
      kind: "bare-lease-less-call",
      symbol: "legacy-registry-call",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 148,
    },
    {
      kind: "canonical-constructor",
      symbol: "DocumentSession",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 713,
    },
    {
      kind: "concrete-exposure",
      symbol: "DocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 78,
    },
    {
      kind: "concrete-exposure",
      symbol: "document-session-registry-implementation",
      file: "apps/app/src/core/editor/account-document-session-runtime.ts",
      line: 11,
    },
    {
      kind: "concrete-exposure",
      symbol: "document-session-registry-implementation",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 10,
    },
    {
      kind: "facade-definition",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 81,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 8,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 5,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 23,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 27,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 5,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 35,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 25,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 36,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 18,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 9,
    },
    {
      kind: "facade-import",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 20,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 68,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 21,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 33,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 44,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 51,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 188,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 225,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 37,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 148,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 260,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 73,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 184,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 197,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 208,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 120,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 469,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 30,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 138,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 145,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 146,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 148,
    },
    {
      kind: "facade-reference",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 153,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 67,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 97,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/test-support/UntitledLifecycleRig.ts",
      line: 272,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 52,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 52,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler.ts",
      line: 98,
    },
    {
      kind: "legacy-owner",
      symbol: "destroyRoom",
      file: "apps/app/src/features/project/context/untitled-reconciler.ts",
      line: 687,
    },
    {
      kind: "legacy-owner",
      symbol: "revokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 66,
    },
    {
      kind: "legacy-owner",
      symbol: "revokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 96,
    },
    {
      kind: "raw-authority",
      symbol: "BroadcastChannel",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 233,
    },
    {
      kind: "raw-authority",
      symbol: "BroadcastChannel",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 234,
    },
    {
      kind: "raw-authority",
      symbol: "BroadcastChannel",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 236,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 24,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 169,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 218,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 265,
    },
    {
      kind: "raw-authority",
      symbol: "CrossContextLockManager",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 910,
    },
    {
      kind: "raw-authority",
      symbol: "meridian:f1d:v1:",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 16,
    },
    {
      kind: "raw-authority",
      symbol: "navigator.locks",
      file: "apps/app/src/core/editor/document-session-cross-context-coordination.ts",
      line: 220,
    },
    {
      kind: "transitional",
      symbol: "TemporaryUnfencedDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 51,
    },
    {
      kind: "transitional",
      symbol: "TemporaryUnfencedDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 73,
    },
    {
      kind: "transitional",
      symbol: "TemporaryUnfencedDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 81,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 8,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/client/query/useDraftReviewMutations.ts",
      line: 68,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 5,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 21,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/change-trail-navigation.ts",
      line: 33,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 81,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 23,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 44,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/core/editor/passage-navigation.ts",
      line: 51,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 27,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 188,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/DraftReviewProvider.tsx",
      line: 225,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 5,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/chat/useAuthorizedChangeTrailDetail.ts",
      line: 37,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 35,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 148,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/EditorView.tsx",
      line: 260,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 25,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/editor/surfaces/peer-marks/PeerMarkPopover.tsx",
      line: 73,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 36,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 184,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 197,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/ContextEditorMountHost.tsx",
      line: 208,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 18,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 120,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/IdentityPlacementField.tsx",
      line: 469,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 9,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/context/untitled-reconciler-browser.ts",
      line: 30,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 20,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 138,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 145,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 146,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 148,
    },
    {
      kind: "transitional",
      symbol: "getDocumentSessionRegistry",
      file: "apps/app/src/features/project/mobile/MobileDocumentHost.tsx",
      line: 153,
    },
    {
      kind: "transitional",
      symbol: "temporaryAttachDetached",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 919,
    },
    {
      kind: "transitional",
      symbol: "temporaryAttachDetached",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 89,
    },
    {
      kind: "transitional",
      symbol: "temporaryGet",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 908,
    },
    {
      kind: "transitional",
      symbol: "temporaryGet",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 86,
    },
    {
      kind: "transitional",
      symbol: "temporaryGet",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 87,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetDetached",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 915,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetDetached",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 920,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetDetached",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 88,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 873,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 912,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 916,
    },
    {
      kind: "transitional",
      symbol: "temporaryGetLive",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 995,
    },
    {
      kind: "transitional",
      symbol: "temporaryObserve",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 988,
    },
    {
      kind: "transitional",
      symbol: "temporaryObserve",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 95,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 926,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 965,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 93,
    },
    {
      kind: "transitional",
      symbol: "temporaryPeek",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 94,
    },
    {
      kind: "transitional",
      symbol: "temporaryRelease",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 984,
    },
    {
      kind: "transitional",
      symbol: "temporaryRelease",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 92,
    },
    {
      kind: "transitional",
      symbol: "temporaryRestartUnavailableRoom",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 925,
    },
    {
      kind: "transitional",
      symbol: "temporaryRestartUnavailableRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 90,
    },
    {
      kind: "transitional",
      symbol: "temporaryRetain",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 942,
    },
    {
      kind: "transitional",
      symbol: "temporaryRetain",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 91,
    },
    {
      kind: "transitional",
      symbol: "temporaryRevokeRoom",
      file: "apps/app/src/core/editor/document-session-registry-implementation.ts",
      line: 973,
    },
    {
      kind: "transitional",
      symbol: "temporaryRevokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 96,
    },
    {
      kind: "transitional",
      symbol: "temporaryRevokeRoom",
      file: "apps/app/src/core/editor/document-session-registry.ts",
      line: 97,
    },
    {
      kind: "unqualified-owner",
      symbol: "roomSessionPersistenceKey",
      file: "apps/app/src/core/editor/document-session.ts",
      line: 65,
    },
    {
      kind: "unqualified-owner",
      symbol: "useCatalogWorkingSetReconciler",
      file: "apps/app/src/features/project/ProjectView.tsx",
      line: 43,
    },
    {
      kind: "unqualified-owner",
      symbol: "useCatalogWorkingSetReconciler",
      file: "apps/app/src/features/project/ProjectView.tsx",
      line: 127,
    },
    {
      kind: "unqualified-owner",
      symbol: "useCatalogWorkingSetReconciler",
      file: "apps/app/src/features/project/context/useCatalogWorkingSetReconciler.ts",
      line: 79,
    },
  ],
} as const;
